openapi: 3.1.0
x-stoplight:
  id: 91a4ao3uk9mo3
info:
  title: Import export Selfnet
  version: '0.4'
  description: |-
    # SELFNET IMPORT EXPORT API documentation

    The HTTP status codes returned by the endpoints follow these rules:
    - If the flow is correct, returns positive response code
    - If the flow is incorrect, returns negative response code 
    - If the flow breaks for some reason (DB connection, malformed input, etc..), returns negative response
servers:
  - url: 'https://mxp-import-export-sn.dev.icadsistemi.com/v1'
paths:
  /cards:
    get:
      summary: Get cards data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cards'
      operationId: get-cards
      description: Used to get one or more cards.
      parameters:
        - schema:
            type: string
          in: query
          name: supplier_code
          required: true
          description: Mandatory supplier_code
        - schema:
            type: string
          in: query
          name: customer_code
          description: Optional customer code
        - schema:
            type: string
          in: query
          description: Optional card code
          name: card_code
        - schema:
            type: string
          in: query
          name: card_code_type
          description: Optional card type code
    post:
      summary: Insert/Update cards
      operationId: post-cards
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Cards'
      description: Used to upsert one or more cards.
  /cards/transfer:
    post:
      summary: Transfer credit between two cards
      operationId: cards-transfer
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Transfer credit between two rechargeable cards
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                supplier_code:
                  type: string
                source_card_pan:
                  type: string
                target_card_pan:
                  type: string
              required:
                - supplier_code
                - source_card_pan
                - target_card_pan
    parameters: []
  /cards/articles:
    put:
      summary: Link cards to articles
      operationId: put-cards-articles
      responses:
        '200':
          description: OK
      description: Used to link cards to oil articles.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CardsArticlesInput'
  /customers:
    get:
      summary: Get customer data
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  supplier_code:
                    type: string
                  address:
                    type: string
                  city:
                    type: string
                  province:
                    type: string
                  telephone_number:
                    type: string
                  email:
                    type: string
                  vat:
                    type: string
                  fiscal_code:
                    type: string
                  total_recharge_credit:
                    type: number
                  is_enabled:
                    type: boolean
                  max_period_credit:
                    type: number
                  debit_period:
                    type: number
                  payment_periodicity_code:
                    type: string
                  payment_method_code:
                    type: string
                  payment_terms_code:
                    type: string
                  exposure:
                    type: number
      operationId: get-customers
      description: Get on customers filtered by input data
      parameters:
        - schema:
            type: string
          in: query
          name: supplier_code
          required: true
        - schema:
            type: string
          in: query
          name: customer_code
    post:
      summary: Create customer
      operationId: post-customers
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              supplier_code:
                type: string
              type: object
              properties:
                supplier_code:
                  type: string
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                      name:
                        type: string
                      address:
                        type: string
                      city:
                        type: string
                      province:
                        type: string
                      zip_code:
                        type: string
                      telephone_number:
                        type: string
                      email:
                        type: string
                      vat:
                        type: string
                      is_enabled:
                        type: string
                      max_period_credit:
                        type: number
                    required:
                      - code
                      - name
              required:
                - supplier_code
  /fuelstations:
    put:
      summary: Update fuel stations data
      operationId: put-fuelstations
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  supplier_code:
                    type: string
                  fuel_station_code:
                    type: string
                  name:
                    type: string
                  address:
                    type: string
                  zip_code:
                    type: string
                  province:
                    type: string
                  office_number:
                    type: string
                required:
                  - supplier_code
                  - fuel_station_code
  /recharges:
    get:
      summary: Get recharges history
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transaction_number:
                      type: string
                    datetime:
                      type: string
                    bill:
                      type: string
                    rebate:
                      type: string
                    residue:
                      type: string
                    terminal_id:
                      type: string
                    result:
                      type: string
                    customer_code:
                      type: string
                    card_pan:
                      type: string
                    card_code:
                      type: string
                    customer_name:
                      type: string
      operationId: get-recharges
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: supplier_code
          required: true
          description: Mandatory supplier_code
        - schema:
            type: string
          in: query
          name: card_pan
          description: Optional card PAN
        - schema:
            type: string
          in: query
          name: date_start
          description: Unix time format.
        - schema:
            type: string
          in: query
          name: date_end
          description: Unix time format.
    post:
      summary: Request a new recharge
      operationId: post-recharges
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '409':
          description: 'Conflict, progressive number already registered in the system'
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                supplier_code:
                  type: string
                progressive_number:
                  type: integer
                  description: 'Unique progressive number for recharge request by supplier_code [optional]'
                recharges:
                  type: array
                  items:
                    type: object
                    properties:
                      card_pan:
                        type: string
                      amount:
                        type: number
                    required:
                      - card_pan
                      - amount
              required:
                - supplier_code
                - recharges
      description: Request to recharge a list of cards
components:
  schemas:
    Cards:
      title: Cards
      x-stoplight:
        id: b1c9dd5f464dd
      type: object
      properties:
        batch_number:
          type: integer
          description: Optional field.
        number:
          type: integer
          description: 'Card number. Max value: 999999'
        supplier_code:
          type: string
        card_type_code:
          type: integer
        expire_datetime:
          type: string
          format: date-time
        max_period_credit:
          type: number
        customer_code:
          type: string
          description: 'If not set, the card won''t be linked to a customer'
        vehicle_plate:
          type: string
        max_daily_credit:
          type: number
        has_km_request:
          type: boolean
        has_km_check:
          type: boolean
        has_driver_request:
          type: boolean
        is_enabled:
          type: boolean
        indoor:
          type: boolean
        outdoor:
          type: boolean
        pan:
          type: string
          description: 'If set, this will be the card pan. If not set, the pan will be calculated server side.'
      required:
        - number
        - supplier_code
        - card_type_code
        - expire_datetime
        - is_enabled
    CardsArticlesInput:
      title: CardsArticlesInput
      x-stoplight:
        id: trh1om38odsnb
      type: object
      properties:
        supplier_code:
          type: string
        cards:
          type: array
          items:
            type: object
            properties:
              card_code:
                type: integer
              card_type_code:
                type: integer
              article_is_code:
                type: array
                items:
                  type: object
                  properties:
                    is_code:
                      type: string
                    is_enabled:
                      type: boolean
      required:
        - supplier_code
  securitySchemes:
    Cognito:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security:
  - API Key - 1: []
